branches:
  only:
  - master

version: '0.1.3.{build}'

dotnet_csproj:
  version_prefix: '0.1.3'
  patch: true
  file: 'src\**\*.csproj'

configuration: Release

skip_tags: true

clone_depth: 1

test: off

build_script:
  - ps: .\build.ps1

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: .\artifacts\*.nupkg
    name: NuGet

#deploy:
#- provider: NuGet
#  api_key:
#    secure: JSqGLy0Lt9FkZHBfucPd7MmOi/FpogM4nv529p+X0XCtsBa+5ulAOvUNt9F+gUfy
#  skip_symbols: true